# This workflow does a clean install of node dependencies,  
# cache/restore them, build the source code, and run tests across Node.js 24.x and 26.x
# See: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Dependabot alerts do not work with actions SHA pinning!
# "For GitHub Actions, alerts are only generated for actions that use semantic versioning, not SHA versioning."
# https://docs.github.com/en/code-security/concepts/supply-chain-security/dependabot-alerts#detection-of-insecure-dependencies


name: Clean Install, Build, Run All Tests

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [24, 26]
        # Supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
